name: ncov-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - mafft
  - augur
  - pysam
  - r-base=3.6.1
  - iqtree<2
  - bioconductor-ggtree=2.0.0
  - r-patchwork=1.0.0
  - r-ggforce=0.3.1
  - bedtools
  - samtools
  - newick_utils
  - pip=19.3.1
  - pip:
      - dendropy>=4.4.0
      - git+https://github.com/hCoV-2019/lineages.git
      - git+https://github.com/hCoV-2019/pangolin.git
      - git+https://github.com/rdeborja/ncov_parser.git
