name: ncov-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - mafft
  - augur
  - pysam
  - r-base=3.6.1
  - iqtree<2
  - bioconductor-ggtree=2.0.0
  - r-argparse
  - r-patchwork=1.0.0
  - r-ggforce=0.3.1
  - bedtools
  - samtools
  - newick_utils
  - pip=19.3.1
  - minimap2
  - pdftoppm
  - numpy=1.19.1
  - biopython
  - pip:
      - dendropy>=4.4.0
      - pyvcf
      - git+https://github.com/hCoV-2019/lineages.git
      - git+https://github.com/hCoV-2019/pangolin.git
      - git+https://github.com/cov-lineages/pangoLEARN.git
      - git+https://github.com/cov-ert/datafunk.git
