name: ncov-qc
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - mafft
  - augur
  - pysam
  - r-base=3.6.3
  - iqtree<2
  - bioconductor-ggtree=2.0.0
  - r-argparse
  - r-patchwork=1.0.0
  - r-ggforce=0.3.1
  - bedtools
  - samtools
  - parasail-python
  - newick_utils
  - pip=19.3.1
  - minimap2
  - poppler
  - gofasta
  - numpy=1.19.1
  - biopython=1.77
  - snpeff=5.0-0
  - icu=68.1
  - boost-cpp=1.74.0
  - usher
  - pip:
      - dendropy>=4.4.0
      - pyvcf3
      - ncov-parser
      - git+https://github.com/cov-lineages/pangolin.git
      - git+https://github.com/cov-lineages/pangolin-data.git
      - git+https://github.com/cov-lineages/constellations.git
      - git+https://github.com/cov-lineages/scorpio.git
      - git+https://github.com/jts/ncov-watch.git
